swagger: "2.0"
info:
  title: Todo Service
  description: Service that manage todo.
  version: ""
host: localhost:8088
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /hello/{name}:
    get:
      tags:
      - todo
      summary: hello todo
      operationId: todo#hello
      parameters:
      - name: name
        in: path
        description: Name
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            type: string
      schemes:
      - http
  /todo/{id}:
    get:
      tags:
      - todo
      summary: show todo
      operationId: todo#show
      parameters:
      - name: id
        in: path
        description: ID
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/TodoShowResponseBody'
      schemes:
      - http
definitions:
  TodoShowResponseBody:
    title: 'Mediatype identifier: todo; view=default'
    type: object
    properties:
      id:
        type: integer
        description: ID
        example: 2838235209218037211
        format: int64
      is_done:
        type: boolean
        description: IsDone
        example: false
      title:
        type: string
        description: Title
        example: Voluptatem vel libero debitis.
    description: ShowResponseBody result type (default view)
    example:
      id: 2368934434395686797
      is_done: true
      title: In praesentium totam voluptatibus adipisci eos vel.
