openapi: 3.0.3
info:
  title: Todo Service
  description: Service that manage todo.
  version: "1.0"
servers:
- url: http://localhost:8088
paths:
  /hello/{name}:
    get:
      tags:
      - todo
      summary: hello todo
      operationId: todo#hello
      parameters:
      - name: name
        in: path
        description: Name
        required: true
        schema:
          type: string
          description: Name
          example: Officia vero fugiat cumque.
        example: Iure dolore.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: string
                example: Ea ut voluptatum.
              example: Est voluptatibus cum et quasi magni.
  /todo/{id}:
    get:
      tags:
      - todo
      summary: show todo
      operationId: todo#show
      parameters:
      - name: id
        in: path
        description: ID
        required: true
        schema:
          type: integer
          description: ID
          example: 5029119594382279781
          format: int64
        example: 3130548282279138188
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
              example:
                id: 151656195322834973
                is_done: true
                title: Aperiam minima mollitia.
components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: integer
          description: ID
          example: 4118086402290002102
          format: int64
        is_done:
          type: boolean
          description: IsDone
          example: true
        title:
          type: string
          description: Title
          example: Ea quia rerum enim cupiditate eaque nihil.
      example:
        id: 7041713459340774230
        is_done: true
        title: Enim nisi itaque eveniet consequatur aut ipsam.
tags:
- name: todo
  description: Service that manage todo.
